# Test on multiple versions (R > 3.0)
language: R
# Enable package cache
cache: packages
# Disable sudo to ensure container infrasturcture
sudo: false
# Build on OS
matrix:
 include:
   - os: linux
     r: oldrel
   - os: linux
     r: release
     env: R_CODECOV=true
   - os: linux
     r: devel
   - os: osx
     r: release
     latex: false
   - os: osx
     r: release
     osx_image: xcode8.2
     latex: false
     r_packages:
      - Rcpp
# fast_finish: true
# To CRAN, warnings **are** errors.
warnings_are_errors: true
