# Test on multiple versions (R > 3.0)
language: R
# Enable package cache
cache: packages
# Disable sudo to ensure container infrasturcture
sudo: false
# Build on OS
matrix:
 include:
   - os: linux
     r: release
     r_packages: covr
   - os: linux
     r: devel
   - os: osx
     r: release
   - os: osx
     r: devel
     r_packages:
      - Rcpp
 fast_finish: true
# To CRAN, warnings **are** errors.
warnings_are_errors: true
