# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
# Test on multiple versions (R > 3.0)
r:
- release
- devel
# Enable package cache
cache: packages
# Disable sudo to ensure container infrasturcture
sudo: false
# Build on OS
os:
- linux
- osx
  osx_image: xcode8
# To CRAN, warnings **are** errors.
warnings_are_errors: true
